- hosts: localhost
  become: True
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes
        
    - name: Delete file index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Create empty index.html file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: line insert to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: '3.1'

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        
    - name: Generate shell script 
      vars:
        webshell: |
          statuscode="$(curl -o /dev/null --silent --head --write-out '%{http_code}' localhost)"
          echo "$(date "+%F %T") status is $statuscode"  >> /home/ubuntu/weblog.txt
      copy:
        dest: /home/ubuntu/weblog.sh
        content: "{{ webshell }}"
        mode: '0554'
        owner: ubuntu
        group: ubuntu
        
    - name: Run CRON job every min.
      cron:
        name: "status check"
        user: "ubuntu"
        weekday: "*"
        minute: "*"
        hour: "*"
        job: "/home/ubuntu/weblog.sh"
        state: present
